In [1]:
import numpy as np


In [4]:
a=np.zeros((2,3,4),dtype='int')

In [5]:
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [6]:
b=np.ones((2,3,4),dtype='int')

In [7]:
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [11]:
c=np.arange(1,100)

In [12]:
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
aa=np.array([2,3.3,5.5,-6.4,-2.2,2.4])

In [14]:
aa

array([ 2. ,  3.3,  5.5, -6.4, -2.2,  2.4])

In [15]:
a[1]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
aa=np.array([[2,3.3,5.5,-6.4,-2.2,2.4]])

In [17]:
aa

array([[ 2. ,  3.3,  5.5, -6.4, -2.2,  2.4]])

In [22]:
d=np.array([[2,3.3,5.5,-6.4,-2.2,2.4],[2,3.3,5.5,-6.4,-2.2,2.4],[2,3.3,5.5,-6.4,-2.2,2.4]])

In [23]:
d

array([[ 2. ,  3.3,  5.5, -6.4, -2.2,  2.4],
       [ 2. ,  3.3,  5.5, -6.4, -2.2,  2.4],
       [ 2. ,  3.3,  5.5, -6.4, -2.2,  2.4]])

In [32]:
aa[:,3],aa[1:4, 0:4],aa[1:, 2]

(array([-6.4]),
 array([], shape=(0, 4), dtype=float64),
 array([], dtype=float64))

In [33]:
arr=np.array((range(4),range(10,14)))

In [34]:
arr.shape

(2, 4)

In [37]:
arr.max()

13

In [38]:
arr.min()

0

In [39]:
arr.size

8

In [40]:
arr.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [43]:
arr.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [44]:
arr.dtype

dtype('int32')

In [46]:
arr=arr.astype('float64')

In [47]:
arr.dtype

dtype('float64')

In [48]:
h=arr.flatten()

In [49]:
h

array([ 0.,  1.,  2.,  3., 10., 11., 12., 13.])

In [50]:
x=np.arange(1,21)

In [51]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [76]:
aar=np.array([[1,2,3,4],[5,6,7,8]])

In [77]:
aar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
aar.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
aar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
f=np.array([[1,2]])

In [64]:
f

array([[1, 2]])